/*
Copyright 2020 Adobe. All rights reserved.
Copyright 2021 Gaoding. All rights reserved.
This file is licensed to you under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License. You may obtain a copy
of the License at http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software distributed under
the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR REPRESENTATIONS
OF ANY KIND, either express or implied. See the License for the specific language
governing permissions and limitations under the License.
*/
export { EditorAddIcon } from './icons/EditorAdd.js';
export { EditorAlertIcon } from './icons/EditorAlert.js';
export { EditorAlertFillIcon } from './icons/EditorAlertFill.js';
export { EditorAlignArrangeHorizIcon } from './icons/EditorAlignArrangeHoriz.js';
export { EditorAlignArrangeVertIcon } from './icons/EditorAlignArrangeVert.js';
export { EditorAlignHorizBottomIcon } from './icons/EditorAlignHorizBottom.js';
export { EditorAlignHorizMiddleIcon } from './icons/EditorAlignHorizMiddle.js';
export { EditorAlignHorizTopIcon } from './icons/EditorAlignHorizTop.js';
export { EditorAlignVertCenterIcon } from './icons/EditorAlignVertCenter.js';
export { EditorAlignVertLeftIcon } from './icons/EditorAlignVertLeft.js';
export { EditorAlignVertRightIcon } from './icons/EditorAlignVertRight.js';
export { EditorAnimationIcon } from './icons/EditorAnimation.js';
export { EditorArrowDownIcon } from './icons/EditorArrowDown.js';
export { EditorArrowLeftIcon } from './icons/EditorArrowLeft.js';
export { EditorArrowRightIcon } from './icons/EditorArrowRight.js';
export { EditorBackspaceIcon } from './icons/EditorBackspace.js';
export { EditorCheckIcon } from './icons/EditorCheck.js';
export { EditorCheckFillIcon } from './icons/EditorCheckFill.js';
export { EditorCloseIcon } from './icons/EditorClose.js';
export { EditorCloseFullIcon } from './icons/EditorCloseFull.js';
export { EditorCloudDoneIcon } from './icons/EditorCloudDone.js';
export { EditorCloudOffIcon } from './icons/EditorCloudOff.js';
export { EditorColorpickerIcon } from './icons/EditorColorpicker.js';
export { EditorCommandIcon } from './icons/EditorCommand.js';
export { EditorContactsIcon } from './icons/EditorContacts.js';
export { EditorContainerIcon } from './icons/EditorContainer.js';
export { EditorCornerIcon } from './icons/EditorCorner.js';
export { EditorCornerRadiusBottomLeftIcon } from './icons/EditorCornerRadiusBottomLeft.js';
export { EditorCornerRadiusBottomRightIcon } from './icons/EditorCornerRadiusBottomRight.js';
export { EditorCornerRadiusTopLeftIcon } from './icons/EditorCornerRadiusTopLeft.js';
export { EditorCornerRadiusTopRightIcon } from './icons/EditorCornerRadiusTopRight.js';
export { EditorCropIcon } from './icons/EditorCrop.js';
export { EditorDataBarchartIcon } from './icons/EditorDataBarchart.js';
export { EditorDesktopIcon } from './icons/EditorDesktop.js';
export { EditorDirectionDownIcon } from './icons/EditorDirectionDown.js';
export { EditorDirectionLeftIcon } from './icons/EditorDirectionLeft.js';
export { EditorDirectionRightIcon } from './icons/EditorDirectionRight.js';
export { EditorDirectionUpIcon } from './icons/EditorDirectionUp.js';
export { EditorDragHandleIcon } from './icons/EditorDragHandle.js';
export { EditorEyeIcon } from './icons/EditorEye.js';
export { EditorEyeDisplayIcon } from './icons/EditorEyeDisplay.js';
export { EditorEyeOffIcon } from './icons/EditorEyeOff.js';
export { EditorFileFolderIcon } from './icons/EditorFileFolder.js';
export { EditorFocusIcon } from './icons/EditorFocus.js';
export { EditorFormatCenterIcon } from './icons/EditorFormatCenter.js';
export { EditorFormatIndentDecreaseIcon } from './icons/EditorFormatIndentDecrease.js';
export { EditorFormatIndentIncreaseIcon } from './icons/EditorFormatIndentIncrease.js';
export { EditorFormatJustifiedIcon } from './icons/EditorFormatJustified.js';
export { EditorFormatLeftIcon } from './icons/EditorFormatLeft.js';
export { EditorFormatListBulletedIcon } from './icons/EditorFormatListBulleted.js';
export { EditorFormatListNumberedIcon } from './icons/EditorFormatListNumbered.js';
export { EditorFormatPacingLinesIcon } from './icons/EditorFormatPacingLines.js';
export { EditorFormatRightIcon } from './icons/EditorFormatRight.js';
export { EditorFormatSpacingLetterIcon } from './icons/EditorFormatSpacingLetter.js';
export { EditorHelpIcon } from './icons/EditorHelp.js';
export { EditorHelpFillIcon } from './icons/EditorHelpFill.js';
export { EditorHomeIcon } from './icons/EditorHome.js';
export { EditorImageIcon } from './icons/EditorImage.js';
export { EditorInfoIcon } from './icons/EditorInfo.js';
export { EditorInfoFillIcon } from './icons/EditorInfoFill.js';
export { EditorKeylineIcon } from './icons/EditorKeyline.js';
export { EditorLabelCIcon } from './icons/EditorLabelC.js';
export { EditorLabelDIcon } from './icons/EditorLabelD.js';
export { EditorLabelGIcon } from './icons/EditorLabelG.js';
export { EditorLabelVIcon } from './icons/EditorLabelV.js';
export { EditorLabelXIcon } from './icons/EditorLabelX.js';
export { EditorLabelYIcon } from './icons/EditorLabelY.js';
export { EditorLayersIcon } from './icons/EditorLayers.js';
export { EditorLayoutIcon } from './icons/EditorLayout.js';
export { EditorLinkIcon } from './icons/EditorLink.js';
export { EditorLockedIcon } from './icons/EditorLocked.js';
export { EditorMenuIcon } from './icons/EditorMenu.js';
export { EditorMoreHorizIcon } from './icons/EditorMoreHoriz.js';
export { EditorNoneIcon } from './icons/EditorNone.js';
export { EditorOpenFullIcon } from './icons/EditorOpenFull.js';
export { EditorPageFooterIcon } from './icons/EditorPageFooter.js';
export { EditorPageHeaderIcon } from './icons/EditorPageHeader.js';
export { EditorPagesIcon } from './icons/EditorPages.js';
export { EditorParagraphIcon } from './icons/EditorParagraph.js';
export { EditorQrCodeIcon } from './icons/EditorQrCode.js';
export { EditorRedoIcon } from './icons/EditorRedo.js';
export { EditorRemoveIcon } from './icons/EditorRemove.js';
export { EditorRotateLeftIcon } from './icons/EditorRotateLeft.js';
export { EditorSettingsIcon } from './icons/EditorSettings.js';
export { EditorShiftIcon } from './icons/EditorShift.js';
export { EditorSliderInvisibleIcon } from './icons/EditorSliderInvisible.js';
export { EditorSmartphoneIcon } from './icons/EditorSmartphone.js';
export { EditorStarIcon } from './icons/EditorStar.js';
export { EditorStopCircleIcon } from './icons/EditorStopCircle.js';
export { EditorTabletMacIcon } from './icons/EditorTabletMac.js';
export { EditorTextIcon } from './icons/EditorText.js';
export { EditorTextBoldIcon } from './icons/EditorTextBold.js';
export { EditorTextDeletelineIcon } from './icons/EditorTextDeleteline.js';
export { EditorTextItalyIcon } from './icons/EditorTextItaly.js';
export { EditorTextScaleIcon } from './icons/EditorTextScale.js';
export { EditorTextUnderlineIcon } from './icons/EditorTextUnderline.js';
export { EditorThemeIcon } from './icons/EditorTheme.js';
export { EditorTuneIcon } from './icons/EditorTune.js';
export { EditorUndoIcon } from './icons/EditorUndo.js';
export { EditorUnlockedIcon } from './icons/EditorUnlocked.js';
export { EditorVideoIcon } from './icons/EditorVideo.js';
export { EditorViewDayIcon } from './icons/EditorViewDay.js';
export { setCustomTemplateLiteralTag } from './custom-tag.js';
