/*
Copyright 2020 Adobe. All rights reserved.
Copyright 2021 Gaoding. All rights reserved.
This file is licensed to you under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License. You may obtain a copy
of the License at http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software distributed under
the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR REPRESENTATIONS
OF ANY KIND, either express or implied. See the License for the specific language
governing permissions and limitations under the License.
*/
export { AddIcon } from './icons/Add.js';
export { AlertFillIcon } from './icons/AlertFill.js';
export { AlertIcon } from './icons/Alert.js';
export { AlignArrangeHorizIcon } from './icons/AlignArrangeHoriz.js';
export { AlignArrangeVertIcon } from './icons/AlignArrangeVert.js';
export { AlignHorizBottomIcon } from './icons/AlignHorizBottom.js';
export { AlignHorizMiddleIcon } from './icons/AlignHorizMiddle.js';
export { AlignHorizTopIcon } from './icons/AlignHorizTop.js';
export { AlignVertCenterIcon } from './icons/AlignVertCenter.js';
export { AlignVertLeftIcon } from './icons/AlignVertLeft.js';
export { AlignVertRightIcon } from './icons/AlignVertRight.js';
export { AnimationIcon } from './icons/Animation.js';
export { ArrowDownIcon } from './icons/ArrowDown.js';
export { ArrowLeftIcon } from './icons/ArrowLeft.js';
export { ArrowRightIcon } from './icons/ArrowRight.js';
export { BackspaceIcon } from './icons/Backspace.js';
export { CheckFillIcon } from './icons/CheckFill.js';
export { CheckIcon } from './icons/Check.js';
export { CloseFullIcon } from './icons/CloseFull.js';
export { CloseIcon } from './icons/Close.js';
export { CloudDoneIcon } from './icons/CloudDone.js';
export { CloudOffIcon } from './icons/CloudOff.js';
export { ColorpickerIcon } from './icons/Colorpicker.js';
export { CommandIcon } from './icons/Command.js';
export { ContactsIcon } from './icons/Contacts.js';
export { ContainerIcon } from './icons/Container.js';
export { CornerRadiusBottomLeftIcon } from './icons/CornerRadiusBottomLeft.js';
export { CornerRadiusBottomRightIcon } from './icons/CornerRadiusBottomRight.js';
export { CornerRadiusTopLeftIcon } from './icons/CornerRadiusTopLeft.js';
export { CornerRadiusTopRightIcon } from './icons/CornerRadiusTopRight.js';
export { CornerIcon } from './icons/Corner.js';
export { CropIcon } from './icons/Crop.js';
export { DataBarchartIcon } from './icons/DataBarchart.js';
export { DesktopIcon } from './icons/Desktop.js';
export { DirectionDownIcon } from './icons/DirectionDown.js';
export { DirectionLeftIcon } from './icons/DirectionLeft.js';
export { DirectionRightIcon } from './icons/DirectionRight.js';
export { DirectionUpIcon } from './icons/DirectionUp.js';
export { DragHandleIcon } from './icons/DragHandle.js';
export { EyeDisplayIcon } from './icons/EyeDisplay.js';
export { EyeOffIcon } from './icons/EyeOff.js';
export { EyeIcon } from './icons/Eye.js';
export { FileFolderIcon } from './icons/FileFolder.js';
export { FocusIcon } from './icons/Focus.js';
export { FormatCenterIcon } from './icons/FormatCenter.js';
export { FormatIndentDecreaseIcon } from './icons/FormatIndentDecrease.js';
export { FormatIndentIncreaseIcon } from './icons/FormatIndentIncrease.js';
export { FormatJustifiedIcon } from './icons/FormatJustified.js';
export { FormatLeftIcon } from './icons/FormatLeft.js';
export { FormatListBulletedIcon } from './icons/FormatListBulleted.js';
export { FormatListNumberedIcon } from './icons/FormatListNumbered.js';
export { FormatPacingLinesIcon } from './icons/FormatPacingLines.js';
export { FormatRightIcon } from './icons/FormatRight.js';
export { FormatSpacingLetterIcon } from './icons/FormatSpacingLetter.js';
export { HelpFillIcon } from './icons/HelpFill.js';
export { HelpIcon } from './icons/Help.js';
export { HomeIcon } from './icons/Home.js';
export { ImageIcon } from './icons/Image.js';
export { InfoFillIcon } from './icons/InfoFill.js';
export { InfoIcon } from './icons/Info.js';
export { KeylineIcon } from './icons/Keyline.js';
export { LabelCIcon } from './icons/LabelC.js';
export { LabelDIcon } from './icons/LabelD.js';
export { LabelGIcon } from './icons/LabelG.js';
export { LabelVIcon } from './icons/LabelV.js';
export { LabelXIcon } from './icons/LabelX.js';
export { LabelYIcon } from './icons/LabelY.js';
export { LayersIcon } from './icons/Layers.js';
export { LayoutIcon } from './icons/Layout.js';
export { LinkIcon } from './icons/Link.js';
export { LockedIcon } from './icons/Locked.js';
export { MenuIcon } from './icons/Menu.js';
export { MoreHorizIcon } from './icons/MoreHoriz.js';
export { NoneIcon } from './icons/None.js';
export { OpenFullIcon } from './icons/OpenFull.js';
export { PageFooterIcon } from './icons/PageFooter.js';
export { PageHeaderIcon } from './icons/PageHeader.js';
export { PagesIcon } from './icons/Pages.js';
export { ParagraphIcon } from './icons/Paragraph.js';
export { QrCodeIcon } from './icons/QrCode.js';
export { RedoIcon } from './icons/Redo.js';
export { RemoveIcon } from './icons/Remove.js';
export { RotateLeftIcon } from './icons/RotateLeft.js';
export { SettingsIcon } from './icons/Settings.js';
export { ShiftIcon } from './icons/Shift.js';
export { SliderInvisibleIcon } from './icons/SliderInvisible.js';
export { SmartphoneIcon } from './icons/Smartphone.js';
export { StarIcon } from './icons/Star.js';
export { StopCircleIcon } from './icons/StopCircle.js';
export { TabletMacIcon } from './icons/TabletMac.js';
export { TextBoldIcon } from './icons/TextBold.js';
export { TextDeletelineIcon } from './icons/TextDeleteline.js';
export { TextItalyIcon } from './icons/TextItaly.js';
export { TextScaleIcon } from './icons/TextScale.js';
export { TextUnderlineIcon } from './icons/TextUnderline.js';
export { TextIcon } from './icons/Text.js';
export { ThemeIcon } from './icons/Theme.js';
export { TuneIcon } from './icons/Tune.js';
export { UndoIcon } from './icons/Undo.js';
export { UnlockedIcon } from './icons/Unlocked.js';
export { VideoIcon } from './icons/Video.js';
export { ViewDayIcon } from './icons/ViewDay.js';
export { setCustomTemplateLiteralTag } from './custom-tag.js';
