/*
Copyright 2020 Adobe. All rights reserved.
Copyright 2021 Gaoding. All rights reserved.
This file is licensed to you under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License. You may obtain a copy
of the License at http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software distributed under
the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR REPRESENTATIONS
OF ANY KIND, either express or implied. See the License for the specific language
governing permissions and limitations under the License.
*/
export { IconAdd } from './elements/Add.js';
export { IconAlertFill } from './elements/AlertFill.js';
export { IconAlert } from './elements/Alert.js';
export { IconAlignArrangeHoriz } from './elements/AlignArrangeHoriz.js';
export { IconAlignArrangeVert } from './elements/AlignArrangeVert.js';
export { IconAlignHorizBottom } from './elements/AlignHorizBottom.js';
export { IconAlignHorizMiddle } from './elements/AlignHorizMiddle.js';
export { IconAlignHorizTop } from './elements/AlignHorizTop.js';
export { IconAlignVertCenter } from './elements/AlignVertCenter.js';
export { IconAlignVertLeft } from './elements/AlignVertLeft.js';
export { IconAlignVertRight } from './elements/AlignVertRight.js';
export { IconAnimation } from './elements/Animation.js';
export { IconArrowDown } from './elements/ArrowDown.js';
export { IconArrowLeft } from './elements/ArrowLeft.js';
export { IconArrowRight } from './elements/ArrowRight.js';
export { IconBackspace } from './elements/Backspace.js';
export { IconCheckFill } from './elements/CheckFill.js';
export { IconCheck } from './elements/Check.js';
export { IconCloseFull } from './elements/CloseFull.js';
export { IconClose } from './elements/Close.js';
export { IconCloudDone } from './elements/CloudDone.js';
export { IconCloudOff } from './elements/CloudOff.js';
export { IconColorpicker } from './elements/Colorpicker.js';
export { IconCommand } from './elements/Command.js';
export { IconContacts } from './elements/Contacts.js';
export { IconContainer } from './elements/Container.js';
export { IconCornerRadiusBottomLeft } from './elements/CornerRadiusBottomLeft.js';
export { IconCornerRadiusBottomRight } from './elements/CornerRadiusBottomRight.js';
export { IconCornerRadiusTopLeft } from './elements/CornerRadiusTopLeft.js';
export { IconCornerRadiusTopRight } from './elements/CornerRadiusTopRight.js';
export { IconCorner } from './elements/Corner.js';
export { IconCrop } from './elements/Crop.js';
export { IconDataBarchart } from './elements/DataBarchart.js';
export { IconDesktop } from './elements/Desktop.js';
export { IconDirectionDown } from './elements/DirectionDown.js';
export { IconDirectionLeft } from './elements/DirectionLeft.js';
export { IconDirectionRight } from './elements/DirectionRight.js';
export { IconDirectionUp } from './elements/DirectionUp.js';
export { IconDragHandle } from './elements/DragHandle.js';
export { IconEyeDisplay } from './elements/EyeDisplay.js';
export { IconEyeOff } from './elements/EyeOff.js';
export { IconEye } from './elements/Eye.js';
export { IconFileFolder } from './elements/FileFolder.js';
export { IconFocus } from './elements/Focus.js';
export { IconFormatCenter } from './elements/FormatCenter.js';
export { IconFormatIndentDecrease } from './elements/FormatIndentDecrease.js';
export { IconFormatIndentIncrease } from './elements/FormatIndentIncrease.js';
export { IconFormatJustified } from './elements/FormatJustified.js';
export { IconFormatLeft } from './elements/FormatLeft.js';
export { IconFormatListBulleted } from './elements/FormatListBulleted.js';
export { IconFormatListNumbered } from './elements/FormatListNumbered.js';
export { IconFormatPacingLines } from './elements/FormatPacingLines.js';
export { IconFormatRight } from './elements/FormatRight.js';
export { IconFormatSpacingLetter } from './elements/FormatSpacingLetter.js';
export { IconHelpFill } from './elements/HelpFill.js';
export { IconHelp } from './elements/Help.js';
export { IconHome } from './elements/Home.js';
export { IconImage } from './elements/Image.js';
export { IconInfoFill } from './elements/InfoFill.js';
export { IconInfo } from './elements/Info.js';
export { IconKeyline } from './elements/Keyline.js';
export { IconLabelC } from './elements/LabelC.js';
export { IconLabelD } from './elements/LabelD.js';
export { IconLabelG } from './elements/LabelG.js';
export { IconLabelV } from './elements/LabelV.js';
export { IconLabelX } from './elements/LabelX.js';
export { IconLabelY } from './elements/LabelY.js';
export { IconLayers } from './elements/Layers.js';
export { IconLayout } from './elements/Layout.js';
export { IconLink } from './elements/Link.js';
export { IconLocked } from './elements/Locked.js';
export { IconMenu } from './elements/Menu.js';
export { IconMoreHoriz } from './elements/MoreHoriz.js';
export { IconNone } from './elements/None.js';
export { IconOpenFull } from './elements/OpenFull.js';
export { IconPageFooter } from './elements/PageFooter.js';
export { IconPageHeader } from './elements/PageHeader.js';
export { IconPages } from './elements/Pages.js';
export { IconParagraph } from './elements/Paragraph.js';
export { IconQrCode } from './elements/QrCode.js';
export { IconRedo } from './elements/Redo.js';
export { IconRemove } from './elements/Remove.js';
export { IconRotateLeft } from './elements/RotateLeft.js';
export { IconSettings } from './elements/Settings.js';
export { IconShift } from './elements/Shift.js';
export { IconSliderInvisible } from './elements/SliderInvisible.js';
export { IconSmartphone } from './elements/Smartphone.js';
export { IconStar } from './elements/Star.js';
export { IconStopCircle } from './elements/StopCircle.js';
export { IconTabletMac } from './elements/TabletMac.js';
export { IconTextBold } from './elements/TextBold.js';
export { IconTextDeleteline } from './elements/TextDeleteline.js';
export { IconTextItaly } from './elements/TextItaly.js';
export { IconTextScale } from './elements/TextScale.js';
export { IconTextUnderline } from './elements/TextUnderline.js';
export { IconText } from './elements/Text.js';
export { IconTheme } from './elements/Theme.js';
export { IconTune } from './elements/Tune.js';
export { IconUndo } from './elements/Undo.js';
export { IconUnlocked } from './elements/Unlocked.js';
export { IconVideo } from './elements/Video.js';
export { IconViewDay } from './elements/ViewDay.js';
